Importamos

In [134]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score 
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split, GridSearchCV, RandomizedSearchCV, cross_validate, KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [135]:
X_raw = pd.read_csv("/Users/juanfelipe/Documents/Datos_Taller1/Punto1/X_train.csv", header = 0, low_memory=False)
y_raw = pd.read_csv("/Users/juanfelipe/Documents/Datos_Taller1/Punto1/y_train.csv", header = 0, low_memory=False)

In [136]:
X_raw.head()

,Id,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,...,age,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq
0,ID_1c08ffb74,NaN,0,4,0,1,1,0,NaN,0,...,36,36,1296,1,0,0,0.250000,0.0000,36.00,1296
1,ID_503cfc817,70000.0,0,4,0,1,1,0,NaN,0,...,45,36,2025,9,25,1,2.250000,0.2500,30.25,2025
2,ID_59e21a8c4,NaN,0,3,0,1,1,1,1.0,1,...,36,121,1296,9,81,1,9.000000,0.2500,100.00,1296
3,ID_a5bedc6c4,NaN,0,4,0,1,1,1,1.0,1,...,68,0,4624,16,0,1,4.000000,9.0000,36.00,4624
4,ID_95533259b,90000.0,0,6,0,1,1,1,2.0,0,...,97,0,9409,25,121,0,2.777778,0.0625,64.00,9409

In [137]:
y_raw.head()

   Target
0       1
1       4
2       4
3       4
4       4

Asignamos el target ara que sea binario

In [138]:
y = y_raw.copy()
y["Target"]=y["Target"].apply(lambda x: 1 if x == 1 or x == 2 else 0)
y.head()

   Target
0       1
1       0
2       0
3       0
4       0

In [139]:
X_raw.head()

,Id,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,...,age,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq
0,ID_1c08ffb74,NaN,0,4,0,1,1,0,NaN,0,...,36,36,1296,1,0,0,0.250000,0.0000,36.00,1296
1,ID_503cfc817,70000.0,0,4,0,1,1,0,NaN,0,...,45,36,2025,9,25,1,2.250000,0.2500,30.25,2025
2,ID_59e21a8c4,NaN,0,3,0,1,1,1,1.0,1,...,36,121,1296,9,81,1,9.000000,0.2500,100.00,1296
3,ID_a5bedc6c4,NaN,0,4,0,1,1,1,1.0,1,...,68,0,4624,16,0,1,4.000000,9.0000,36.00,4624
4,ID_95533259b,90000.0,0,6,0,1,1,1,2.0,0,...,97,0,9409,25,121,0,2.777778,0.0625,64.00,9409

Re definimos variables para que sean numericas

In [140]:
X_ed = X_raw.replace("no", 99)
X_ed = X_ed.replace("yes", 1)
X_ed.head()

,Id,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,...,age,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq
0,ID_1c08ffb74,NaN,0,4,0,1,1,0,NaN,0,...,36,36,1296,1,0,0,0.250000,0.0000,36.00,1296
1,ID_503cfc817,70000.0,0,4,0,1,1,0,NaN,0,...,45,36,2025,9,25,1,2.250000,0.2500,30.25,2025
2,ID_59e21a8c4,NaN,0,3,0,1,1,1,1.0,1,...,36,121,1296,9,81,1,9.000000,0.2500,100.00,1296
3,ID_a5bedc6c4,NaN,0,4,0,1,1,1,1.0,1,...,68,0,4624,16,0,1,4.000000,9.0000,36.00,4624
4,ID_95533259b,90000.0,0,6,0,1,1,1,2.0,0,...,97,0,9409,25,121,0,2.777778,0.0625,64.00,9409

In [148]:
string_cols = X_ed.select_dtypes(include=['object']).columns.tolist()
print(string_cols)
print(X_raw[string_cols].dtypes)

['Id', 'idhogar']
Id         str
idhogar    str
dtype: object

/var/folders/m9/8glbgjx57n9ft9qzy1pc32k40000gn/T/ipykernel_8174/3607015577.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_cols = X_ed.select_dtypes(include=['object']).columns.tolist()

In [142]:
X_ed['dependency']=X_ed['dependency'].astype(float)
X_ed['edjefe']=X_ed['edjefe'].astype(float)
X_ed['edjefa']=X_ed['edjefa'].astype(float)

Verificamos missing values para ver como accionar

In [149]:
missing_pct = X_ed.isna().mean().sort_values(ascending=False) * 100

missing_pct = missing_pct[missing_pct > 0]
missing_pct

rez_esc      82.838008
SQBmeaned     0.027906
meaneduc      0.027906
dtype: float64

cambiamos que si v18q1 es NaN es = 0 tablets

In [144]:
X_ed['v18q1'] = X_ed['v18q1'].fillna(0)
X_ed.head()

,Id,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,...,age,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq
0,ID_1c08ffb74,NaN,0,4,0,1,1,0,0.0,0,...,36,36,1296,1,0,0,0.250000,0.0000,36.00,1296
1,ID_503cfc817,70000.0,0,4,0,1,1,0,0.0,0,...,45,36,2025,9,25,1,2.250000,0.2500,30.25,2025
2,ID_59e21a8c4,NaN,0,3,0,1,1,1,1.0,1,...,36,121,1296,9,81,1,9.000000,0.2500,100.00,1296
3,ID_a5bedc6c4,NaN,0,4,0,1,1,1,1.0,1,...,68,0,4624,16,0,1,4.000000,9.0000,36.00,4624
4,ID_95533259b,90000.0,0,6,0,1,1,1,2.0,0,...,97,0,9409,25,121,0,2.777778,0.0625,64.00,9409

In [145]:
X_ed['v2a1_reg'] = X_ed['v2a1'].notna().astype(int)
X_ed[['v2a1', 'v2a1_reg']].head()

/var/folders/m9/8glbgjx57n9ft9qzy1pc32k40000gn/T/ipykernel_8174/4280733851.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X_ed['v2a1_reg'] = X_ed['v2a1'].notna().astype(int)

      v2a1  v2a1_reg
0      NaN         0
1  70000.0         1
2      NaN         0
3      NaN         0
4  90000.0         1

In [146]:
X_ed=X_ed.drop('v2a1', axis=1)
X_ed.head()

In [151]:
X_ed['rezago'] = X_ed['rez_esc'].notna().astype(int)
X_ed[['rez_esc', 'rezago']].head()

   rez_esc  rezago
0      NaN       0
1      NaN       0
2      NaN       0
3      NaN       0
4      NaN       0

In [ ]:
# crear columna 'gran rezago' en X_ed: 1 si rez_esc >= 3, else 0
X_ed['gran rezago'] = (X_ed['rez_esc'] >= 3).astype(int)
X_ed[['rez_esc', 'gran rezago']].head()